### ISSUE TITLE
Intermittent non-zero exit status 123 

### ISSUE THREAD

**Issue by sundeepgoel72** [Breakthrough/DVR-Scan#103]
**Bug/Issue Description:**

Running dvr-scan  via a windows batch file to process a large number of files. Periodically processing stops, and CTRL-C has to be pressed multiple times to resume. On pressing CTRL-C following error log is printed, pointing to exit code 123 from ffmpeg. 

any pointers on what could be causing it ? 

----------------------

--- Logging error ---
Traceback (most recent call last):
  File "dvr_scan\scanner.py", line 929, in _encode_thread
  File "dvr_scan\scanner.py", line 907, in _on_motion_event
  File "dvr_scan\scanner.py", line 166, in _extract_event_ffmpeg
  File "subprocess.py", line 415, in check_output
  File "subprocess.py", line 516, in run
subprocess.CalledProcessError: Command '['ffmpeg', '-y', '-nostdin', '-v', 'error', '-hwaccel', 'dxva2', '-ss', '00:01:08.400', '-i', 'H:\\Surveilance\\Ch8\\2020-10-17\\ch8-20201017125205_20201017125401.dav', '-t', '00:00:16.040', '-map', '0', '-c:v', 'libx265', '-preset', 'fast', '-crf', '28', '-c:a', 'aac', '-sn', 'H:\\Surveilance\\Ch8\\2020-10-17\\extracted\\ch8-20201017125205_20201017125401.DSME_0006.mp4']' returned non-zero exit status 123.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tqdm\contrib\logging.py", line 30, in emit
  File "logging\__init__.py", line 1069, in flush
OSError: [Errno 22] Invalid argument
Call stack:
  File "threading.py", line 890, in _bootstrap
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "dvr_scan\scanner.py", line 934, in _encode_thread
  File "logging\__init__.py", line 1493, in critical
  File "logging\__init__.py", line 1589, in _log
  File "logging\__init__.py", line 1599, in handle
  File "logging\__init__.py", line 1661, in callHandlers
  File "logging\__init__.py", line 954, in handle
  File "tqdm\contrib\logging.py", line 34, in emit
Message: 'Fatal error: Exception raised in encode thread.'
Arguments: ()
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='cp1252'>
OSError: [Errno 22] Invalid argument

**Comment by Breakthrough** [comment]
Are you using the same version of `ffmpeg` in the location where the `dvr-scan.exe` file is?  Could you share the full command you're using to invoke the script?  If you process only the above video, does the same error occur when running dvr-scan, or does this only happen from a batch file?

Lastly, **please add `--verbosity debug` to your command** when running DVR-Scan, and provide the output after adding that.  Also see if the issue occurs when setting a logfile, and attach that as well.  Thank you.

**Comment by sundeepgoel72** [comment]
> so I suspect your batch file is doing something with stdout/stderr or the logfile has an invalid path.

Batch file is a below.  The error occurs on DSME_0006.mp4, implies that first 5 extracts have run fine, indicates issue probably not with batch file.

I'll reply to other points shortly.

```
@echo off
for /d %%i in (%1) do call :$DoSomething "%%i"
exit /B

::**************************************************
:$DoSomething
::**************************************************
mkdir %~1\extracted

for %%f in (%~1\*.dav); do (
	echo %%f | findstr /c:"delete"  1>nul
	if errorlevel 1 (
		dvr-scan -c "E:\sg-bin\python\PersonDetection\dvr-scan-config-ch8.txt" -i %%f --logfile %~1\extracted\motionlog.txt -d %~1\extracted | findstr /c:"No motion events detected" && ren %%f %%~nf-delete%%~xf  || echo Motion in %%f >>  %~1\extracted\Nomotionlog.txt
)
	
exit /B
```

**Comment by sundeepgoel72** [comment]
Ran DVR-scan outside of batch, get following at the last extract

[DVR-Scan] Failed to decode 6 frame(s) from video, timestamps may be incorrect. Try re-encoding or remuxing video (e.g. ffmpeg -i video.mp4 -c:v copy out.mp4). See https://github.com/Breakthrough/DVR-Scan/issues/62 for details.
[DVR-Scan] Processed 2898 frames read in 67.4 secs (avg 43.0 FPS).
[DVR-Scan] Detected 6 motion events in input.
[DVR-Scan] List of motion events:

DVR-scan doesnt "hang" but exits normally (logfile attached) - so wonder why the batch file is hanging ...
[motionlog.txt](https://github.com/Breakthrough/DVR-Scan/files/9391120/motionlog.txt)

**Comment by Breakthrough** [comment]
Can you let me know if you get the same issue if you *uninstall* the `tqdm` module?  Also are there any special characters in the logfile path?

This seems to be failing after changing logging to work correctly with the progress bar.  If the root cause of the issue cannot be determined, a potential workaround would be to add a config file to disable the progress bar.  A command line argument should probably be added to disable the progress bar anyways as it may not work under all systems.  If you are using the Python version of DVR-Scan, you can simply uninstall the `tqdm` module.

This means DVR-Scan won't show any progress bars, but it will help determine if this is the reason the batch file is failing or not.
