### ISSUE TITLE
Problem installing from master on Debian 10.4 amd64

### ISSUE THREAD

**Issue by Catfriend1** [Breakthrough/DVR-Scan#30]
Hi,

I took these steps:
apt-get update
apt-get install -y python3 python3-numpy python3-opencv python3-setuptools python3-tqdm
git clone "https://github.com/Breakthrough/DVR-Scan.git" "/root/install/dvr-scan"
echo "$(cd "/root/install/dvr-scan/"; python3 "setup.py" install)"

```
zip_safe flag not set; analyzing archive contents...
running install
running bdist_egg
running egg_info
creating DVR_Scan.egg-info
writing DVR_Scan.egg-info/PKG-INFO
writing dependency_links to DVR_Scan.egg-info/dependency_links.txt
writing entry points to DVR_Scan.egg-info/entry_points.txt
writing requirements to DVR_Scan.egg-info/requires.txt
writing top-level names to DVR_Scan.egg-info/top_level.txt
writing manifest file 'DVR_Scan.egg-info/SOURCES.txt'
reading manifest file 'DVR_Scan.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'DVR_Scan.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/dvr_scan
copying dvr_scan/cli.py -> build/lib/dvr_scan
copying dvr_scan/platform.py -> build/lib/dvr_scan
copying dvr_scan/__init__.py -> build/lib/dvr_scan
copying dvr_scan/__main__.py -> build/lib/dvr_scan
copying dvr_scan/timecode.py -> build/lib/dvr_scan
copying dvr_scan/scanner.py -> build/lib/dvr_scan
copying dvr_scan/../LICENSE -> build/lib/dvr_scan/..
copying dvr_scan/../LICENSE-OPENCV -> build/lib/dvr_scan/..
copying dvr_scan/../LICENSE-NUMPY -> build/lib/dvr_scan/..
copying dvr_scan/../package-info.rst -> build/lib/dvr_scan/..
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
copying build/lib/LICENSE -> build/bdist.linux-x86_64/egg
copying build/lib/package-info.rst -> build/bdist.linux-x86_64/egg
copying build/lib/LICENSE-OPENCV -> build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/dvr_scan
copying build/lib/dvr_scan/cli.py -> build/bdist.linux-x86_64/egg/dvr_scan
copying build/lib/dvr_scan/platform.py -> build/bdist.linux-x86_64/egg/dvr_scan
copying build/lib/dvr_scan/__init__.py -> build/bdist.linux-x86_64/egg/dvr_scan
copying build/lib/dvr_scan/__main__.py -> build/bdist.linux-x86_64/egg/dvr_scan
copying build/lib/dvr_scan/timecode.py -> build/bdist.linux-x86_64/egg/dvr_scan
copying build/lib/dvr_scan/scanner.py -> build/bdist.linux-x86_64/egg/dvr_scan
copying build/lib/LICENSE-NUMPY -> build/bdist.linux-x86_64/egg
byte-compiling build/bdist.linux-x86_64/egg/dvr_scan/cli.py to cli.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/dvr_scan/platform.py to platform.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/dvr_scan/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/dvr_scan/__main__.py to __main__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/dvr_scan/timecode.py to timecode.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/dvr_scan/scanner.py to scanner.cpython-37.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying DVR_Scan.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying DVR_Scan.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying DVR_Scan.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying DVR_Scan.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying DVR_Scan.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying DVR_Scan.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating dist
creating 'dist/DVR_Scan-1.0.1-py3.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing DVR_Scan-1.0.1-py3.7.egg
Removing /usr/local/lib/python3.7/dist-packages/DVR_Scan-1.0.1-py3.7.egg
Copying DVR_Scan-1.0.1-py3.7.egg to /usr/local/lib/python3.7/dist-packages
DVR-Scan 1.0.1 is already the active version in easy-install.pth
Installing dvr-scan script to /usr/local/bin

Installed /usr/local/lib/python3.7/dist-packages/DVR_Scan-1.0.1-py3.7.egg
Processing dependencies for DVR-Scan==1.0.1
Searching for numpy==1.16.2
Best match: numpy 1.16.2
Adding numpy 1.16.2 to easy-install.pth file
Installing f2py script to /usr/local/bin
Installing f2py3 script to /usr/local/bin
Installing f2py3.7 script to /usr/local/bin
```

python3 /usr/local/bin/dvr-scan --version

```
Traceback (most recent call last):
  File "/usr/local/bin/dvr-scan", line 11, in <module>
    load_entry_point('DVR-Scan==1.0.1', 'console_scripts', 'dvr-scan')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/usr/local/lib/python3.7/dist-packages/DVR_Scan-1.0.1-py3.7.egg/dvr_scan/__init__.py", line 32, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/usr/local/lib/python3.7/dist-packages/DVR_Scan-1.0.1-py3.7.egg/dvr_scan/scanner.py", line 36, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/usr/local/lib/python3.7/dist-packages/DVR_Scan-1.0.1-py3.7.egg/dvr_scan/platform.py", line 33, in <module>
    #    <see CVS and SVN checkin messages for history>
AttributeError: module 'cv2' has no attribute 'cv'
```

How can I fix the error?

**Comment by Catfriend1** [comment]
Hmmm I can execute "python3 /usr/local/bin/dvr-scan --version" if I remove the following part of "platform.py":

```
# Compatibility fix for OpenCV < 3.0
if (int(cv2.__version__[0]) <= 3):
    cv2.CAP_PROP_FRAME_WIDTH = cv2.cv.CV_CAP_PROP_FRAME_WIDTH
    cv2.CAP_PROP_FRAME_HEIGHT = cv2.cv.CV_CAP_PROP_FRAME_HEIGHT
    cv2.CAP_PROP_FPS = cv2.cv.CV_CAP_PROP_FPS
    cv2.CAP_PROP_POS_MSEC = cv2.cv.CV_CAP_PROP_POS_MSEC
    cv2.CAP_PROP_POS_FRAMES = cv2.cv.CV_CAP_PROP_POS_FRAMES
    cv2.CAP_PROP_FRAME_COUNT = cv2.cv.CV_CAP_PROP_FRAME_COUNT
    cv2.VideoWriter_fourcc = cv2.cv.CV_FOURCC
```

Afterwards, I need to do:

```
rm /usr/local/lib/python3.7/dist-packages/DVR_Scan-1.0.1-py3.7.egg
echo "$(cd "/root/install/dvr-scan/"; python3 "setup.py" install)"
python3 /usr/local/bin/dvr-scan --version
-----------------------------------------------
DVR-Scan v1.1-dev
-----------------------------------------------
Copyright (C) 2016-2017 Brandon Castellano
< https://github.com/Breakthrough/DVR-Scan >

This DVR-Scan is licensed under the BSD 2-Clause license; see the
included LICENSE file, or visit the above link for details. This
software uses the following third-party components:
  NumPy: Copyright (C) 2005-2013, Numpy Developers.
 OpenCV: Copyright (C) 2016, Itseez.
THE SOFTWARE IS PROVIDED "AS IS" WITHOUT ANY WARRANTY, EXPRESS OR IMPLIED.

```

**Comment by Breakthrough** [comment]
Hi @Catfriend1;

Could you tell me what the version of OpenCV is reported that you have installed?  You can check by running the following in a Python terminal:

    import cv2
    cv2.__version__

Thanks!

**Comment by Catfriend1** [comment]
Hi @Breakthrough 

I've entered the command and got '3.2.0' on the console.

Thanks for your quick answer and taking care.

**Comment by Breakthrough** [comment]
Hey @Catfriend1;

Looking at this now with a fresh set of eyes, it seems like my version detection functionality isn't correct (I'm using <= instead of <).  I'll tag this as a bug and add it to the list for the next DVR-Scan release.

Should have something in master by the end of the week that fixes this, thank you for letting me know!

**Comment by Catfriend1** [comment]
Hehe, you're great. Just want to say **thank you so much** for this!
It's a perfect match to improve my Yi Camera's motion detection together with https://github.com/roleoroleo/yi-hack-Allwinner/pull/68

**Comment by Breakthrough** [comment]
Fixed in 862e2cce3415a11fa7bc6fde9f7d720e4a976135.

**Comment by Catfriend1** [comment]
:) thank you

**Comment by planetloli** [comment]
please delete issue
