### ISSUE TITLE
El Capitan Python 2.7.15 DVR-Scan Installation Issue

### ISSUE THREAD

**Issue by daBee** [Breakthrough/DVR-Scan#4]
I'm on a `Mac El Capitan 10.11` box.  Very much want to use this software, or at least try it out.  Looks great. I can't get all this working, and I know nothing about `Python`.  

```
$ python --version
Python 2.7.15

$ sudo python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to DVR_Scan.egg-info/requires.txt
writing DVR_Scan.egg-info/PKG-INFO
writing top-level names to DVR_Scan.egg-info/top_level.txt
writing dependency_links to DVR_Scan.egg-info/dependency_links.txt
writing entry points to DVR_Scan.egg-info/entry_points.txt
reading manifest file 'DVR_Scan.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'DVR_Scan.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.11-x86_64/egg
running install_lib
running build_py
creating build/bdist.macosx-10.11-x86_64/egg
creating build/bdist.macosx-10.11-x86_64/egg/dvr_scan
copying build/lib/dvr_scan/__init__.py -> build/bdist.macosx-10.11-x86_64/egg/dvr_scan
copying build/lib/dvr_scan/__main__.py -> build/bdist.macosx-10.11-x86_64/egg/dvr_scan
copying build/lib/dvr_scan/cli.py -> build/bdist.macosx-10.11-x86_64/egg/dvr_scan
copying build/lib/dvr_scan/platform.py -> build/bdist.macosx-10.11-x86_64/egg/dvr_scan
copying build/lib/dvr_scan/scanner.py -> build/bdist.macosx-10.11-x86_64/egg/dvr_scan
copying build/lib/dvr_scan/timecode.py -> build/bdist.macosx-10.11-x86_64/egg/dvr_scan
copying build/lib/LICENSE -> build/bdist.macosx-10.11-x86_64/egg
copying build/lib/LICENSE-NUMPY -> build/bdist.macosx-10.11-x86_64/egg
copying build/lib/LICENSE-OPENCV -> build/bdist.macosx-10.11-x86_64/egg
copying build/lib/package-info.rst -> build/bdist.macosx-10.11-x86_64/egg
byte-compiling build/bdist.macosx-10.11-x86_64/egg/dvr_scan/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/dvr_scan/__main__.py to __main__.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/dvr_scan/cli.py to cli.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/dvr_scan/platform.py to platform.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/dvr_scan/scanner.py to scanner.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/dvr_scan/timecode.py to timecode.pyc
creating build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying DVR_Scan.egg-info/PKG-INFO -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying DVR_Scan.egg-info/SOURCES.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying DVR_Scan.egg-info/dependency_links.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying DVR_Scan.egg-info/entry_points.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying DVR_Scan.egg-info/requires.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying DVR_Scan.egg-info/top_level.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/DVR_Scan-1.0.1-py2.7.egg' and adding 'build/bdist.macosx-10.11-x86_64/egg' to it
removing 'build/bdist.macosx-10.11-x86_64/egg' (and everything under it)
Processing DVR_Scan-1.0.1-py2.7.egg
Removing /usr/local/lib/python2.7/site-packages/DVR_Scan-1.0.1-py2.7.egg
Copying DVR_Scan-1.0.1-py2.7.egg to /usr/local/lib/python2.7/site-packages
DVR-Scan 1.0.1 is already the active version in easy-install.pth
Installing dvr-scan script to /usr/local/bin

Installed /usr/local/lib/python2.7/site-packages/DVR_Scan-1.0.1-py2.7.egg
Processing dependencies for DVR-Scan==1.0.1
Searching for numpy==1.15.4
Best match: numpy 1.15.4
Processing numpy-1.15.4-py2.7-macosx-10.11-x86_64.egg
numpy 1.15.4 is already the active version in easy-install.pth
Installing f2py script to /usr/local/bin

Using /usr/local/lib/python2.7/site-packages/numpy-1.15.4-py2.7-macosx-10.11-x86_64.egg
Finished processing dependencies for DVR-Scan==1.0.1

$ dvr-scan --version
Traceback (most recent call last):
  File "/usr/local/bin/dvr-scan", line 11, in <module>
    load_entry_point('DVR-Scan==1.0.1', 'console_scripts', 'dvr-scan')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.macosx-10.11-x86_64/egg/dvr_scan/__init__.py", line 32, in <module>
  File "build/bdist.macosx-10.11-x86_64/egg/dvr_scan/scanner.py", line 36, in <module>
  File "build/bdist.macosx-10.11-x86_64/egg/dvr_scan/platform.py", line 29, in <module>
    #      Andruk, Just van Rossum, Thomas Heller, Mark R. Levinson, Mark
ImportError: No module named cv2
```
Yes I'm on an old box.  Any chance this could be something simple I could chase?

**Comment by robhulley** [comment]
I have this running on Mojave without issues will check whether it is running Python 2.7 or 3.6 and let you know.

**Comment by hulleyrob** [comment]
Hi i have a feeling that i installed this against Python3 which was itself installed from Homebrew to get it to work. I am on Mojave but cant see any reason why this wouldnt work on El Capitan.
If you just install Python3 from Homebrew then use sudo pythonr setup.py install it should work. 
If not can you post any output?
Rob

**Comment by daBee** [comment]
I don't even remember posting this, to be honest.  I have moved on.

**Comment by Breakthrough** [comment]
Sorry I didn't see this until now...

This is likely because when DVR-Scan was written, I didn't actually include the OpenCV package as a requirement, as at the time there was no binary distribution available on pip that worked reliably on all platforms.  This has since changed, and I should likely update the required packages.  I'll open a new issue to reflect this.

Thanks for the report.
